# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: Hosted Windows 2019 with VS2019

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run scss-once
  displayName: 'sass'

- script: |
    npm run tsc-el-once
  displayName: 'electron'

- script: |
    npm run tsc-app-once
  displayName: 'ts app'

- task: Npm@1
  displayName: test
  inputs:
    command: custom
    verbose: false
    customCommand: 'run test-once'
  timeoutInMinutes: 5

- script: |
    npm run lint
  displayName: 'lint'

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TESTS*.xml'
  inputs:
    testResultsFiles: '**/TESTS*.xml'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage from $(System.DefaultWorkingDirectory)/**/coverage/cobertura.xml'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage/cobertura.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage/report-html'

- script: |
    npm run package
  displayName: 'package'
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: bin'
  inputs:
    PathtoPublish: bin
    ArtifactName: bin
  timeoutInMinutes: 5
